const STORAGE_KEY='chorwacja2027_demo_v1';
const SESSION_KEY='chorwacja2027_session';
const SELECTED_USER_KEY='chorwacja2027_selected_user';
const REMOTE_TRIP_ID='00000000-0000-0000-0000-000000002027';
const deepCopy=o=>JSON.parse(JSON.stringify(o));
const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const PARTICIPANT_NAMES={admin:'Bartosz',u1:'Dominika',u2:'Agnieszka',u3:'Michał',u4:'Karolina',u5:'Damian',u6:'Krzyś'};
const initialData={
 trip:{name:'Chorwacja 2027',destination:'Makarska, Chorwacja',start:'2027-08-15',end:'2027-08-24',people:7,budget:24800,description:'10-dniowy wyjazd busem z Gdańska do Makarskiej.'},
 users:[
  {id:'admin',name:'Bartosz',role:'admin',pin:'2027'},
  {id:'u1',name:'Dominika',role:'user',pin:'1234'},{id:'u2',name:'Agnieszka',role:'user',pin:'1234'},
  {id:'u3',name:'Michał',role:'user',pin:'1234'},{id:'u4',name:'Karolina',role:'user',pin:'1234'},
  {id:'u5',name:'Damian',role:'user',pin:'1234'},{id:'u6',name:'Krzyś',role:'user',pin:'1234'}],
 payments:{admin:3543,u1:2500,u2:3543,u3:1800,u4:3000,u5:3543,u6:2200},
 expenses:[
  {id:'e1',name:'Wynajem busa 9-osobowego',category:'Transport',amount:2500,status:'planned',date:'2027-08-15',owner:'admin',note:'10 dni, odbiór w Gdańsku'},
  {id:'e2',name:'Paliwo — cała trasa',category:'Transport',amount:4300,status:'planned',date:'2027-08-15',owner:'admin',note:'około 3600 km'},
  {id:'e3',name:'Winiety, autostrady i parkingi',category:'Transport',amount:1600,status:'paid',date:'2027-07-12',owner:'admin',note:''},
  {id:'e4',name:'Apartament — 7 nocy',category:'Nocleg',amount:7800,status:'paid',date:'2027-06-18',owner:'admin',note:'Makarska'},
  {id:'e5',name:'Jedzenie i napoje',category:'Jedzenie',amount:4800,status:'planned',date:'2027-08-15',owner:'admin',note:''},
  {id:'e6',name:'Atrakcje i bilety',category:'Atrakcje',amount:2100,status:'planned',date:'2027-08-18',owner:'admin',note:'Biokovo, rejs, Split'},
  {id:'e7',name:'Wyposażenie wspólne',category:'Wyposażenie',amount:900,status:'planned',date:'2027-08-01',owner:'admin',note:''},
  {id:'e8',name:'Rezerwa awaryjna',category:'Inne',amount:800,status:'planned',date:'2027-08-15',owner:'admin',note:''}],
 tasks:[
  {id:'t1',title:'Sprawdzić dowody osobiste i EKUZ',category:'Dokumenty',assignee:'all',doneBy:['admin','u1','u2']},
  {id:'t2',title:'Pobrać mapy offline i playlistę',category:'Transport',assignee:'all',doneBy:['admin','u3']},
  {id:'t3',title:'Potwierdzić rezerwację busa',category:'Rezerwacje',assignee:'admin',doneBy:['admin']},
  {id:'t4',title:'Potwierdzić apartament w Makarskiej',category:'Rezerwacje',assignee:'admin',doneBy:[]},
  {id:'t5',title:'Kupić apteczkę i leki na chorobę lokomocyjną',category:'Zakupy i wyposażenie',assignee:'u2',doneBy:[]},
  {id:'t6',title:'Zabrać ładowarki, powerbanki i rozdzielacz',category:'Zakupy i wyposażenie',assignee:'all',doneBy:['u1','u4']},
  {id:'t7',title:'Przygotować torbę termiczną i wodę na trasę',category:'Zakupy i wyposażenie',assignee:'u5',doneBy:[]},
  {id:'t8',title:'Sprawdzić assistance i ubezpieczenie',category:'Dokumenty',assignee:'admin',doneBy:[]}],
 plan:[
  {id:'p1',day:1,date:'2027-08-15',title:'Start z Gdańska',description:'Odbiór busa, pakowanie i nocny przejazd przez Polskę w kierunku Czech.'},
  {id:'p2',day:2,date:'2027-08-16',title:'Praga i dalsza droga',description:'Poranny przystanek w Pradze, spacer i posiłek. Przejazd przez Austrię i nocleg w busie lub na campingu.'},
  {id:'p3',day:3,date:'2027-08-17',title:'Przyjazd do Makarskiej',description:'Zakwaterowanie, zakupy, odpoczynek i wieczorny spacer promenadą.'},
  {id:'p4',day:4,date:'2027-08-18',title:'Plaże Makarskiej',description:'Dzień plażowy, St. Peter Forest Park i zachód słońca.'},
  {id:'p5',day:5,date:'2027-08-19',title:'Park Przyrody Biokovo',description:'Skywalk Biokovo, punkty widokowe i spokojny wieczór w apartamencie.'},
  {id:'p6',day:6,date:'2027-08-20',title:'Split i Trogir',description:'Wycieczka do pałacu Dioklecjana oraz starego miasta w Trogirze.'},
  {id:'p7',day:7,date:'2027-08-21',title:'Rejs na Brač',description:'Całodniowy rejs, kąpiel i zwiedzanie jednej z wysp.'},
  {id:'p8',day:8,date:'2027-08-22',title:'Omiš i aktywny dzień',description:'Twierdza Mirabela, kanion Cetiny, opcjonalnie rafting lub zipline.'},
  {id:'p9',day:9,date:'2027-08-23',title:'Wyjazd w stronę Polski',description:'Ostatnie kąpiele, sprzątanie apartamentu i popołudniowy start.'},
  {id:'p10',day:10,date:'2027-08-24',title:'Powrót do Gdańska',description:'Przerwy regeneracyjne na trasie, tankowanie i oddanie busa.'}],
 fuel:{distance:3600,consumption:9.5,price:6.45},
 route:[
  {city:'Gdańsk',country:'Polska',note:'Start i odbiór busa',km:0,lat:54.3520,lng:18.6466},
  {city:'Wrocław',country:'Polska',note:'Tankowanie i posiłek',km:480,lat:51.1079,lng:17.0385},
  {city:'Praga',country:'Czechy',note:'Dłuższa przerwa i spacer',km:770,lat:50.0755,lng:14.4378},
  {city:'Wiedeń',country:'Austria',note:'Zmiana kierowcy',km:1100,lat:48.2082,lng:16.3738},
  {city:'Maribor',country:'Słowenia',note:'Odpoczynek przed Chorwacją',km:1350,lat:46.5547,lng:15.6459},
  {city:'Zagrzeb',country:'Chorwacja',note:'Tankowanie i ostatnia zmiana',km:1480,lat:45.8150,lng:15.9819},
  {city:'Makarska',country:'Chorwacja',note:'Cel podróży',km:1800,lat:43.2969,lng:17.0170}]
};
let data=loadData();let currentUser=null;let confirmAction=null;let adminMode=sessionStorage.getItem(SESSION_KEY)==='admin';let remoteSyncReady=false;let remoteSaveTimer=null;let remoteChannel=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function normalizeData(source){const result=source&&typeof source==='object'?deepCopy(source):deepCopy(initialData);result.trip={...deepCopy(initialData.trip),...(result.trip||{})};result.users=(result.users||deepCopy(initialData.users)).map(user=>({...user,name:PARTICIPANT_NAMES[user.id]||user.name}));result.payments=result.payments||deepCopy(initialData.payments);result.tasks=result.tasks||deepCopy(initialData.tasks);result.plan=result.plan||deepCopy(initialData.plan);result.fuel=result.fuel||deepCopy(initialData.fuel);result.route=(result.route||deepCopy(initialData.route)).map(stop=>({...stop,...(initialData.route.find(x=>x.city===stop.city)||{}),note:stop.note,km:stop.km}));result.expenses=(result.expenses||[]).map(e=>({...e,participants:e.participants?.length?e.participants:result.users.map(u=>u.id)}));return result}
function loadData(){let stored;try{stored=JSON.parse(localStorage.getItem(STORAGE_KEY))}catch{}return normalizeData(stored||initialData)}
function saveLocalData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function saveData(){saveLocalData();if(!remoteSyncReady||!window.tripSupabase)return;clearTimeout(remoteSaveTimer);remoteSaveTimer=setTimeout(pushRemoteData,180)}
async function pushRemoteData(){if(!window.tripSupabase)return;const {error}=await window.tripSupabase.from('trip_state').update({data:deepCopy(data),updated_at:new Date().toISOString()}).eq('id',REMOTE_TRIP_ID);if(error){console.error('Błąd synchronizacji danych:',error);toast('Nie udało się zsynchronizować danych')}}
async function initTripSync(){if(!window.tripSupabase||remoteSyncReady)return;const {data:row,error}=await window.tripSupabase.from('trip_state').select('data').eq('id',REMOTE_TRIP_ID).single();if(error){console.error('Nie udało się pobrać wspólnych danych:',error);toast('Brak połączenia ze wspólnymi danymi');return}remoteSyncReady=true;if(row?.data?.trip){data=normalizeData(row.data);saveLocalData();const remembered=localStorage.getItem(SELECTED_USER_KEY);currentUser=data.users.find(u=>u.id===remembered)||data.users.find(u=>u.role==='user')||data.users[0];renderAll()}else{await pushRemoteData()}remoteChannel=window.tripSupabase.channel('trip-state-sync').on('postgres_changes',{event:'UPDATE',schema:'public',table:'trip_state',filter:`id=eq.${REMOTE_TRIP_ID}`},payload=>{if(!payload.new?.data)return;data=normalizeData(payload.new.data);saveLocalData();const selected=currentUser?.id||localStorage.getItem(SELECTED_USER_KEY);currentUser=data.users.find(u=>u.id===selected)||data.users.find(u=>u.role==='user')||data.users[0];renderAll()}).subscribe();document.body.dataset.sync='online'}
window.initTripSync=initTripSync;
function money(n){return new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',maximumFractionDigits:0}).format(Number(n)||0)}
function fmtDate(s){return new Intl.DateTimeFormat('pl-PL',{day:'numeric',month:'short'}).format(new Date(s+'T12:00:00'))}
function initials(n){return n.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function userName(uid){return data.users.find(u=>u.id===uid)?.name||'Nieznany'}
function isAdmin(){return adminMode}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2400)}
function enterAdmin(){adminMode=true;sessionStorage.setItem(SESSION_KEY,'admin');renderAll();navigate('dashboard');toast('Tryb administratora włączony')}
function logout(){adminMode=false;sessionStorage.removeItem(SESSION_KEY);$('#userDropdown').classList.add('hidden');renderAll();navigate('dashboard');toast('Tryb administratora wyłączony')}
function selectParticipant(uid){const next=data.users.find(u=>u.id===uid);if(!next)return;currentUser=next;localStorage.setItem(SELECTED_USER_KEY,uid);$('#userDropdown').classList.add('hidden');renderAll();toast(`Wybrano profil: ${next.name}`)}
function renderAll(){document.body.classList.toggle('is-admin',isAdmin());$$('.admin-only').forEach(x=>x.classList.toggle('hidden',!isAdmin()));$$('.guest-only').forEach(x=>x.classList.toggle('hidden',isAdmin()));$('#userName').textContent=currentUser.name;$('#welcomeName').textContent=currentUser.name.split(' ')[0];$('#userRole').textContent=isAdmin()?'Administrator':'Uczestnik';$('#rolePill').textContent=isAdmin()?'TRYB ADMINA':'TRYB UŻYTKOWNIKA';$('#userAvatar').textContent=initials(currentUser.name);$('#topTripName').textContent=data.trip.name;$('#topDates').textContent=`${fmtDate(data.trip.start)} – ${fmtDate(data.trip.end)} ${new Date(data.trip.end).getFullYear()}`;renderParticipantOptions();renderDashboard();renderExpenses();renderPayments();renderChecklist();renderPlan();renderRoute();renderSettings()}
function renderParticipantOptions(){$('#participantOptions').innerHTML=data.users.map(u=>`<button data-switch-user="${u.id}" class="${u.id===currentUser.id?'active':''}"><span class="mini-avatar">${initials(u.name)}</span>${escapeHtml(u.name)}${u.id===currentUser.id?' ✓':''}</button>`).join('')}
function totals(){const paid=data.expenses.filter(e=>e.status==='paid').reduce((a,e)=>a+Number(e.amount),0);const planned=data.expenses.reduce((a,e)=>a+Number(e.amount),0);const collected=Object.values(data.payments).reduce((a,x)=>a+Number(x),0);return{paid,planned,collected}}
function relevantTasks(){return data.tasks.filter(t=>isAdmin()||t.assignee==='all'||t.assignee===currentUser.id)}
function taskDone(t){return t.doneBy.includes(currentUser.id)}
function renderDashboard(){const t=totals(),per=data.trip.budget/data.trip.people,pct=Math.min(100,Math.round(t.paid/data.trip.budget*100));const tasks=relevantTasks(),done=tasks.filter(taskDone).length,ready=tasks.length?Math.round(done/tasks.length*100):0;$('#statBudget').textContent=money(data.trip.budget);$('#statPerPerson').textContent=`${money(per)} / osobę`;$('#statSpent').textContent=money(t.paid);$('#statRemaining').textContent=`zostało ${money(data.trip.budget-t.paid)}`;$('#statPaid').textContent=money(t.collected);$('#statPaidProgress').textContent=`${Math.round(t.collected/data.trip.budget*100)}% celu`;$('#statReady').textContent=`${ready}%`;$('#statTasks').textContent=`${done} z ${tasks.length} zadań`;$('#donutPercent').textContent=`${pct}%`;$('#budgetDonut').style.setProperty('--percent',`${pct*3.6}deg`);$('#legendSpent').textContent=money(t.paid);$('#legendPlanned').textContent=money(Math.max(0,t.planned-t.paid));$('#legendFree').textContent=money(Math.max(0,data.trip.budget-t.planned));const days=Math.ceil((new Date(data.trip.start+'T12:00:00')-new Date())/86400000);$('#daysLeft').textContent=Math.max(0,days);$('#dashboardPlan').innerHTML=data.plan.sort((a,b)=>a.day-b.day).slice(0,3).map(p=>`<div class="mini-plan"><div class="day-badge">D${p.day}</div><div><strong>${escapeHtml(p.title)}</strong><span>${fmtDate(p.date)} · ${escapeHtml(p.description.slice(0,62))}${p.description.length>62?'…':''}</span></div></div>`).join('');$('#dashboardPayments').innerHTML=data.users.slice(0,4).map(u=>{const v=Number(data.payments[u.id]||0),p=Math.min(100,Math.round(v/per*100));return`<div class="payment-row"><span class="avatar">${initials(u.name)}</span><div class="payment-meta"><div><strong>${escapeHtml(u.name)}</strong><span>${money(v)}</span></div><div class="progress"><i style="width:${p}%"></i></div></div><strong>${p}%</strong></div>`}).join('');$('#dashboardTasks').innerHTML=tasks.slice(0,4).map(x=>`<label class="preview-task"><input type="checkbox" data-task-toggle="${x.id}" ${taskDone(x)?'checked':''}><span>${escapeHtml(x.title)}</span></label>`).join('')||'<p class="muted">Brak zadań.</p>'}
function renderExpenses(){const q=($('#expenseSearch')?.value||'').toLowerCase(),f=$('#expenseFilter')?.value||'all',t=totals();$('#expenseBudget').textContent=money(data.trip.budget);$('#expensePlanned').textContent=money(t.planned);$('#expensePaid').textContent=money(t.paid);const rows=data.expenses.filter(e=>(f==='all'||e.status===f)&&e.name.toLowerCase().includes(q));$('#expenseEmpty').classList.toggle('hidden',rows.length>0);$('#expenseTable').innerHTML=rows.sort((a,b)=>b.date.localeCompare(a.date)).map(e=>{const own=e.owner===currentUser.id,canEdit=isAdmin()||own,count=e.participants?.length||data.users.length,share=Number(e.amount)/count;return`<tr><td><strong>${escapeHtml(e.name)}</strong><br><small class="muted">${fmtDate(e.date)}</small></td><td><span class="category">${escapeHtml(e.category)}</span></td><td><strong>${money(e.amount)}</strong><span class="expense-split">${count} ${count===1?'osoba':count<5?'osoby':'osób'} · ${money(share)} / os.</span></td><td><span class="status ${e.status}">${e.status==='paid'?'Zapłacone':'Planowane'}</span></td><td>${escapeHtml(userName(e.owner))}</td><td><div class="row-actions">${canEdit?`<button data-edit-expense="${e.id}" title="Edytuj">✎</button>`:''}${isAdmin()?`<button data-delete-expense="${e.id}" title="Usuń">×</button>`:''}</div></td></tr>`}).join('')}
function renderPayments(){const target=data.trip.budget/data.trip.people;$('#paymentTarget').textContent=money(target);$('#paymentsGrid').innerHTML=data.users.map(u=>{const val=Number(data.payments[u.id]||0),pct=Math.min(100,Math.round(val/target*100));return`<article class="person-card"><div class="person-head"><span class="avatar">${initials(u.name)}</span><div><strong>${escapeHtml(u.name)}</strong><small>${u.role==='admin'?'Administrator':'Uczestnik'}</small></div></div><div class="person-money"><strong>${money(val)}</strong><span>z ${money(target)}</span></div><div class="progress"><i style="width:${pct}%"></i></div><small class="muted">${pct}% celu · zostało ${money(Math.max(0,target-val))}</small>${isAdmin()?`<div class="payment-editor"><input type="number" min="0" step="1" value="${val}" aria-label="Wpłata ${escapeHtml(u.name)}"><button class="btn secondary" data-save-payment="${u.id}">Zapisz</button></div>`:''}</article>`}).join('')}
function renderChecklist(){const tasks=relevantTasks(),done=tasks.filter(taskDone).length,pct=tasks.length?Math.round(done/tasks.length*100):0;$('#checklistHelp').textContent=isAdmin()?'Zarządzaj zadaniami grupy i sprawdzaj postęp.':'Możesz oznaczać zadania przypisane Tobie lub całej grupie.';$('#checklistPercent').textContent=`${pct}%`;$('#checklistProgress').style.width=`${pct}%`;$('#checklistCount').textContent=`${done} z ${tasks.length} zadań`;const groups=[...new Set(tasks.map(t=>t.category))];$('#checklistGroups').innerHTML=groups.map(g=>`<section class="check-group"><h2>${escapeHtml(g)}</h2>${tasks.filter(t=>t.category===g).map(t=>`<label class="check-item ${taskDone(t)?'done':''}"><input type="checkbox" data-task-toggle="${t.id}" ${taskDone(t)?'checked':''}><span>${escapeHtml(t.title)}</span><small>${t.assignee==='all'?'Wszyscy':escapeHtml(userName(t.assignee))}</small>${isAdmin()?`<button data-delete-task="${t.id}" title="Usuń">×</button>`:''}</label>`).join('')}</section>`).join('')||'<div class="card empty">Brak zadań do pokazania.</div>';const sel=$('#taskAssignee');sel.innerHTML='<option value="all">Wszyscy</option>'+data.users.map(u=>`<option value="${u.id}">${escapeHtml(u.name)}</option>`).join('')}
function renderPlan(){const sorted=[...data.plan].sort((a,b)=>a.day-b.day);$('#planTimeline').innerHTML=sorted.map(p=>`<article class="plan-entry"><div class="plan-number"><div>DZIEŃ<strong>${p.day}</strong></div></div><div class="plan-content"><header><div><small class="muted">${fmtDate(p.date)}</small><h2>${escapeHtml(p.title)}</h2></div>${isAdmin()?`<div class="row-actions"><button data-edit-plan="${p.id}">✎</button><button data-delete-plan="${p.id}">×</button></div>`:''}</header><p>${escapeHtml(p.description)}</p></div></article>`).join('')}
function routeMapLink(){const stops=data.route.map(s=>encodeURIComponent(`${s.city}, ${s.country}`));return`https://www.google.com/maps/dir/${stops.join('/')}`}
function stopMapLink(stop){return`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${stop.city}, ${stop.country}`)}`}
function renderRoute(){$('#googleRouteLink').href=routeMapLink();$('#routeStops').innerHTML=data.route.map((s,i)=>`<div class="route-stop"><span class="stop-dot">${i+1}</span><div><h3>${escapeHtml(s.city)} <small class="muted">· ${escapeHtml(s.country)}</small></h3><p>${escapeHtml(s.note)} · ${s.km.toLocaleString('pl-PL')} km od startu</p></div><a href="${stopMapLink(s)}" target="_blank" rel="noopener">Pokaż na mapie ↗</a></div>`).join('');$('#fuelDistance').value=data.fuel.distance;$('#fuelConsumption').value=data.fuel.consumption;$('#fuelPrice').value=data.fuel.price;calculateFuel()}
let routeMapInstance=null;
function renderInteractiveMap(){const container=$('#routeMap');if(!container)return;if(!window.L){container.innerHTML='<div class="map-fallback">Nie udało się załadować mapy. Sprawdź połączenie z internetem lub otwórz trasę w Google Maps.</div>';return}if(routeMapInstance){routeMapInstance.invalidateSize();return}container.innerHTML='';routeMapInstance=L.map('routeMap',{scrollWheelZoom:false}).setView([49,17],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(routeMapInstance);const points=data.route.map(s=>[s.lat,s.lng]);data.route.forEach((s,i)=>{const marker=L.divIcon({className:'',html:`<div class="route-map-marker ${i===data.route.length-1?'destination':''}">${i+1}</div>`,iconSize:[30,30],iconAnchor:[15,15]});L.marker([s.lat,s.lng],{icon:marker}).addTo(routeMapInstance).bindPopup(`<div class="map-popup"><h3>${escapeHtml(s.city)}, ${escapeHtml(s.country)}</h3><p>${escapeHtml(s.note)} · ${s.km.toLocaleString('pl-PL')} km od startu</p></div>`)});L.polyline(points,{color:'#147c6f',weight:5,opacity:.82,dashArray:'10 8'}).addTo(routeMapInstance);routeMapInstance.fitBounds(points,{padding:[35,35]})}
function calculateFuel(){const distance=Math.max(0,Number($('#fuelDistance').value)||0),consumption=Math.max(0,Number($('#fuelConsumption').value)||0),price=Math.max(0,Number($('#fuelPrice').value)||0),liters=distance*consumption/100,total=liters*price;$('#routeDistanceStat').textContent=`${distance.toLocaleString('pl-PL')} km`;$('#fuelLiters').textContent=`${liters.toFixed(1).replace('.',',')} l`;$('#fuelTotal').textContent=money(total);$('#fuelPerPerson').textContent=money(total/data.trip.people);return{distance,consumption,price,total}}
function renderSettings(){if(!isAdmin())return;$('#tripName').value=data.trip.name;$('#tripDestination').value=data.trip.destination;$('#tripStart').value=data.trip.start;$('#tripEnd').value=data.trip.end;$('#tripPeople').value=data.trip.people;$('#tripBudget').value=data.trip.budget;$('#tripDescription').value=data.trip.description}
function navigate(name){if(name==='settings'&&!isAdmin())name='dashboard';$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('#mainNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#sidebar').classList.remove('open');if(name==='route')requestAnimationFrame(()=>setTimeout(renderInteractiveMap,0));window.scrollTo({top:0,behavior:'smooth'})}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function selectedExpenseParticipants(){return $$('#expenseParticipants input:checked').map(x=>x.value)}
function updateSplitPreview(){const count=selectedExpenseParticipants().length,amount=Number($('#expenseAmount').value)||0;$('#splitPreview').textContent=count?`${money(amount)} ÷ ${count} = ${money(amount/count)} na osobę`:'Wybierz co najmniej jedną osobę.'}
function openExpense(exp=null){$('#expenseForm').reset();$('#expenseId').value=exp?.id||'';$('#expenseDialogTitle').textContent=exp?'Edytuj wydatek':'Dodaj wydatek';$('#expenseName').value=exp?.name||'';$('#expenseAmount').value=exp?.amount||'';$('#expenseCategory').value=exp?.category||'Transport';$('#expenseStatus').value=exp?.status||'planned';$('#expenseDate').value=exp?.date||new Date().toISOString().slice(0,10);$('#expenseNote').value=exp?.note||'';const selected=exp?.participants||data.users.map(u=>u.id);$('#expenseParticipants').innerHTML=data.users.map(u=>`<label><input type="checkbox" value="${u.id}" ${selected.includes(u.id)?'checked':''}><span>${escapeHtml(u.name)}</span></label>`).join('');updateSplitPreview();$('#expenseDialog').showModal()}
function askConfirm(title,text,action){$('#confirmTitle').textContent=title;$('#confirmText').textContent=text;confirmAction=action;$('#confirmDialog').showModal()}
$('#mainNav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)navigate(b.dataset.view)});document.addEventListener('click',e=>{const go=e.target.closest('[data-goto]');if(go)navigate(go.dataset.goto);const tog=e.target.closest('[data-task-toggle]');if(tog){const t=data.tasks.find(x=>x.id===tog.dataset.taskToggle);if(t){t.doneBy=tog.checked?[...new Set([...t.doneBy,currentUser.id])]:t.doneBy.filter(x=>x!==currentUser.id);saveData();renderDashboard();renderChecklist()}}const ee=e.target.closest('[data-edit-expense]');if(ee){const ex=data.expenses.find(x=>x.id===ee.dataset.editExpense);if(ex&&(isAdmin()||ex.owner===currentUser.id))openExpense(ex)}const de=e.target.closest('[data-delete-expense]');if(de&&isAdmin())askConfirm('Usunąć wydatek?','Ta pozycja zniknie z budżetu.',()=>{data.expenses=data.expenses.filter(x=>x.id!==de.dataset.deleteExpense);saveData();renderAll();toast('Wydatek usunięty')});const dt=e.target.closest('[data-delete-task]');if(dt&&isAdmin())askConfirm('Usunąć zadanie?','Zadanie zostanie usunięte z checklisty.',()=>{data.tasks=data.tasks.filter(x=>x.id!==dt.dataset.deleteTask);saveData();renderAll();toast('Zadanie usunięte')});const sp=e.target.closest('[data-save-payment]');if(sp&&isAdmin()){const input=sp.parentElement.querySelector('input');data.payments[sp.dataset.savePayment]=Math.max(0,Number(input.value));saveData();renderAll();toast('Wpłata zaktualizowana')}const ep=e.target.closest('[data-edit-plan]');if(ep&&isAdmin()){const p=data.plan.find(x=>x.id===ep.dataset.editPlan);$('#planForm').reset();$('#planId').value=p.id;$('#planDialogTitle').textContent='Edytuj punkt planu';$('#planDay').value=p.day;$('#planDate').value=p.date;$('#planTitle').value=p.title;$('#planDescription').value=p.description;$('#planDialog').showModal()}const dp=e.target.closest('[data-delete-plan]');if(dp&&isAdmin())askConfirm('Usunąć punkt planu?','Ten dzień zniknie z harmonogramu.',()=>{data.plan=data.plan.filter(x=>x.id!==dp.dataset.deletePlan);saveData();renderAll();toast('Punkt planu usunięty')})});
document.addEventListener('click',e=>{const sw=e.target.closest('[data-switch-user]');if(sw)selectParticipant(sw.dataset.switchUser)});
$('#addExpenseBtn').onclick=()=>openExpense();$('#expenseSearch').oninput=renderExpenses;$('#expenseFilter').onchange=renderExpenses;
$('#expenseForm').addEventListener('submit',e=>{e.preventDefault();const eid=$('#expenseId').value,old=data.expenses.find(x=>x.id===eid),participants=selectedExpenseParticipants();if(old&&!isAdmin()&&old.owner!==currentUser.id)return;if(!participants.length){updateSplitPreview();return}const item={id:eid||id(),name:$('#expenseName').value.trim(),amount:Number($('#expenseAmount').value),category:$('#expenseCategory').value,status:$('#expenseStatus').value,date:$('#expenseDate').value,note:$('#expenseNote').value.trim(),owner:old?.owner||currentUser.id,participants};if(eid)data.expenses=data.expenses.map(x=>x.id===eid?item:x);else data.expenses.push(item);saveData();$('#expenseDialog').close();renderAll();toast(eid?'Wydatek zaktualizowany':'Wydatek dodany')});
$('#expenseParticipants').addEventListener('change',updateSplitPreview);$('#expenseAmount').addEventListener('input',updateSplitPreview);$('#selectAllParticipants').onclick=()=>{$$('#expenseParticipants input').forEach(x=>x.checked=true);updateSplitPreview()};$('#clearParticipants').onclick=()=>{$$('#expenseParticipants input').forEach(x=>x.checked=false);updateSplitPreview()};
$('#addTaskBtn').onclick=()=>$('#taskDialog').showModal();$('#taskForm').addEventListener('submit',e=>{e.preventDefault();if(!isAdmin())return;data.tasks.push({id:id(),title:$('#taskTitle').value.trim(),category:$('#taskCategory').value,assignee:$('#taskAssignee').value,doneBy:[]});saveData();$('#taskDialog').close();e.target.reset();renderAll();toast('Zadanie dodane')});
$('#addPlanBtn').onclick=()=>{if(!isAdmin())return;$('#planForm').reset();$('#planId').value='';$('#planDialogTitle').textContent='Dodaj punkt planu';$('#planDate').value=data.trip.start;$('#planDialog').showModal()};$('#planForm').addEventListener('submit',e=>{e.preventDefault();if(!isAdmin())return;const pid=$('#planId').value,item={id:pid||id(),day:Number($('#planDay').value),date:$('#planDate').value,title:$('#planTitle').value.trim(),description:$('#planDescription').value.trim()};data.plan=pid?data.plan.map(x=>x.id===pid?item:x):[...data.plan,item];saveData();$('#planDialog').close();renderAll();toast('Plan zaktualizowany')});
$('#tripForm').addEventListener('submit',e=>{e.preventDefault();if(!isAdmin())return;data.trip={name:$('#tripName').value.trim(),destination:$('#tripDestination').value.trim(),start:$('#tripStart').value,end:$('#tripEnd').value,people:Number($('#tripPeople').value),budget:Number($('#tripBudget').value),description:$('#tripDescription').value.trim()};saveData();renderAll();toast('Dane wyjazdu zapisane')});
$('#fuelForm').addEventListener('input',()=>{const result=calculateFuel();data.fuel={distance:result.distance,consumption:result.consumption,price:result.price};saveData()});
$('#saveFuelExpense').onclick=()=>{if(!isAdmin())return;const result=calculateFuel(),existing=data.expenses.find(e=>e.name.toLowerCase().includes('paliwo'));const item={id:existing?.id||id(),name:'Paliwo — cała trasa',category:'Transport',amount:Math.round(result.total),status:existing?.status||'planned',date:existing?.date||data.trip.start,owner:existing?.owner||currentUser.id,note:`${result.distance} km, ${result.consumption} l/100 km, ${result.price} zł/l`,participants:data.users.map(u=>u.id)};data.expenses=existing?data.expenses.map(e=>e.id===existing.id?item:e):[...data.expenses,item];saveData();renderAll();toast('Wydatek paliwowy zaktualizowany')};
$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#confirmCancel').onclick=()=>$('#confirmDialog').close();$('#confirmOk').onclick=()=>{if(confirmAction)confirmAction();confirmAction=null;$('#confirmDialog').close()};$('#logoutBtn').onclick=logout;$('#userBtn').onclick=e=>{e.stopPropagation();$('#userDropdown').classList.toggle('hidden')};document.addEventListener('click',()=>$('#userDropdown').classList.add('hidden'));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
$('#resetData').onclick=()=>{if(isAdmin())askConfirm('Przywrócić dane startowe?','Wszystkie lokalne zmiany zostaną zastąpione danymi demonstracyjnymi.',()=>{data=deepCopy(initialData);saveData();currentUser=data.users.find(u=>u.id==='admin');renderAll();toast('Przywrócono dane startowe')})};
document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.altKey&&e.key.toLowerCase()==='a'){e.preventDefault();if(isAdmin())toast('Masz uprawnienia administratora');else $('#adminLoginDialog').showModal()}});
const rememberedUser=localStorage.getItem(SELECTED_USER_KEY);currentUser=data.users.find(u=>u.id===rememberedUser)||data.users.find(u=>u.role==='user')||data.users[0];renderAll();navigate('dashboard');
